### ISSUE TITLE
Uncaught ReferenceError: type is not defined

### ISSUE THREAD

**Issue by robgardien** [bluehalo/ngx-leaflet-draw#146]
When using ngx-leaflet-draw I receive the following error when drawing a rectangle: 

Uncaught ReferenceError: type is not defined
    at Object.readableArea (leaflet.draw.js:9:12149)
    at NewClass._getTooltipText (leaflet.draw.js:8:18742)
    at NewClass._onMouseMove (leaflet.draw.js:8:17157)
    at NewClass.fire (leaflet-src.js:606:11)
    at NewClass._fireDOMEvent (leaflet-src.js:4565:17)
    at NewClass._handleDOMEvent (leaflet-src.js:4514:10)
    at HTMLDivElement.handler (leaflet-src.js:2799:15)
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:490:34)
readableArea @ leaflet.draw.js:

Other types do not produce the error

**Comment by robgardien** [comment]
RG: I solved it by using <any> type in the options
